# Site settings
title: ZeOmega TechBlog
email: techblog@zeomega.com
description: > # this means to ignore newlines until "baseurl:"
  This is the ZeOmega blog focused on technology.  We'll share our ideas,
  challenges related to our software stack to create Jiva, our
  flagship product.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zeomega.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:

# Build settings
markdown: kramdown
